const theme = {
    colors:{
        article:{
            background:'#fff',
            link:'#ea0f1e',
            subTitle:'#888',
            text:'#000'
        },
        page:{
            background:'#040c18',
            buttons:'#23bd96',
            card:'#323842',
            navigation:{
                desktop:{
                    color:'#8892b0',
                    hoverColor:'#44e3bb'
                },
                mobile:{
                    background:'#44e3bb',
                    color:'#ccd6f6',
                }
            },
            title:'#fafafa', 
            special:'#ffc800',
            subTitle:'#cccfd8'
        }
    },
    fonts:{
        family:{
            primary:"'Inter', sans-serif",
            secondary:"'Fira Code', monospace"
        },
        size:{
            article:{
                content:'1.8rem',
                excerpt:'2.4rem',
                heading:'2rem',
                navigation:'5rem',
                title:{
                    desktop:'5.4rem',
                    mobile:'2.6rem',
                    tablet:'3.52rem'
                },
                subTitle:'2.8rem'
            },
            page:{
                button:'1.4rem',
                content:'1.85rem',
                navigation:'1.4rem',
                title:{
                    desktop:'8rem',
                    mobile:'3.45rem'
                },
                subTitle:'2.2rem'
            }
        },
        weight:{
            article:{
                excerpt:500,
                secondary:700,
                regular:400,
                title:900
            },
            page:{
                regular:400,
                title:700,
                secondary:200,
                subTitle:700
            }
        }
    }
}

export default theme;